- name: Create needed directories
  file:
    path: "{{ weblogic_java_path }}"
    state: directory
    owner: "{{ oracle.user }}"
    group: "{{ oracle.group }}"
- name: untar and install java on required location
  command: tar xzvf /home/oracle/jdk-8u131-linux-x64.tar.gz -C "{{ weblogic_java_path }}"
  become_user: oracle
- name: Add JAVA_HOME environment variariables in bashrc
  lineinfile: dest='/root/.bashrc' line='export JAVA_HOME={{ java_home }}'
- name: Add Java bin folder to path in bashrc
  lineinfile: dest='/root/.bashrc' line='export PATH=$PATH:$JAVA_HOME/bin'
- name: Source .bashrc
  shell: source ~/.bashrc
- name: Add JAVA_HOME environment variariables in bashrc
  lineinfile: dest='/home/oracle/.bashrc' line='export JAVA_HOME={{ java_home }}'
  become_user: oracle
- name: Add Java bin folder to path in bashrc
  lineinfile: dest='/home/oracle/.bashrc' line='export PATH=$PATH:$JAVA_HOME/bin'
  become_user: oracle
- name: Source .bashrc
  shell: source ~/.bashrc
  become_user: oracle


