---

- include: validate.yml

- include: prepare.yml
  become: yes
#  when: weblogic_force_installation or (not weblogic_already_installed)
- include: java.yml
- include: install.yml
  become: yes
  become_user: "{{ oracle.user }}"
#  when: weblogic_force_installation or (not weblogic_already_installed)

- include: create-domain.yml
  become: yes
  become_user: "{{ oracle.user }}"
#  when: not weblogic_domain_already_installed

- include: obi.yml
  become: yes
  become_user: "{{ oracle.user }}"
  tags:
    - wls-install-with-managed-server
#- include: rcu.yml
#  become: yes
#  become_user: "{{ oracle.user }}"
